# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72b2799de43472c49ed1cc3c256e389ebcc10abe03a73dc3555842a6fca1a80dc30bdf7698d43abb7ad587e4aba07577115dd3f6b7859ed06e543777fd73af6a

test:
  secret_key_base: 65505646dcd5df651e1e28ec40d0f6164b1e170c1feff2ab14becdf1f6df8582fdb66fb8f67562e2d5d56a6f078ce5d750171068075e0e9583acfb629db0f977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
